# Generated by Django 5.1.4 on 2024-12-12 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_non_teaching_staff',
            new_name='is_staff',
        ),
    ]
