# Generated by Django 5.1.4 on 2024-12-13 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_rename_is_admin_user_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='total_payable',
            field=models.DecimalField(blank=True, decimal_places=2, default='15000', editable=False, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='studentfees',
            name='balance_amount',
            field=models.DecimalField(decimal_places=2, default=1, editable=False, max_digits=17),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentfees',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default='15000', max_digits=15),
        ),
    ]
