# Generated by Django 5.1.4 on 2024-12-13 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_alter_studentdetails_total_payable_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='certifiation',
            new_name='certification',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='student_fees',
        ),
    ]
