# Generated by Django 5.1.4 on 2024-12-13 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_remove_teachers_grade_gradeofstudents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradeofstudents',
            name='student',
        ),
        migrations.RemoveField(
            model_name='gradeofstudents',
            name='teachers',
        ),
        migrations.AddField(
            model_name='teachers',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.gradeofstudents'),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.gradeofstudents'),
        ),
    ]
