# Generated by Django 5.1.4 on 2024-12-13 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_remove_gradeofstudents_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.gradeofstudents'),
        ),
    ]
