# Generated by Django 5.1.4 on 2024-12-13 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_alter_studentdetails_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gradeofstudents',
            old_name='grade',
            new_name='grades',
        ),
    ]
