# Generated by Django 5.1.4 on 2024-12-13 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_rename_grade_gradeofstudents_grades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='student',
        ),
    ]
