# Generated by Django 5.1.4 on 2024-12-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_remove_teachers_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='guardian',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
