# Generated by Django 5.1.4 on 2024-12-15 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_studentdetails_guardian'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfees',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentfees',
            name='total_paid_so_far',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
