# Generated by Django 5.1.4 on 2024-12-15 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_studentfees_total_paid_studentfees_total_paid_so_far'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfees',
            name='total_paid',
        ),
        migrations.RemoveField(
            model_name='studentfees',
            name='total_paid_so_far',
        ),
    ]
