# Generated by Django 5.1.4 on 2024-12-16 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0015_remove_studentfees_total_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='library_id',
            field=models.CharField(blank=True, max_length=90, null=True, unique=True),
        ),
    ]
