# Generated by Django 5.1.4 on 2024-12-16 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0016_library_library_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='librarian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.librarian'),
        ),
    ]
