# Generated by Django 5.1.4 on 2024-12-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0017_alter_library_librarian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfees',
            name='balance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=17, null=True),
        ),
    ]
